/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Windows;

/**
 *
 * @author BRANDON
 */
public class PrincipalWindowPracticing extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalWindowPracticing
     */
    public PrincipalWindowPracticing() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitle = new javax.swing.JLabel();
        jLabelProyectTitle = new javax.swing.JLabel();
        jButtonSelectProyect = new javax.swing.JButton();
        jButtonMyProyect = new javax.swing.JButton();
        jLabelDocumentationTitle = new javax.swing.JLabel();
        jButtonscheduleAdd = new javax.swing.JButton();
        jButtonPartialReportAdd = new javax.swing.JButton();
        jButtonPersonalSoftwareProcessAdd = new javax.swing.JButton();
        jLabelSelectIcon = new javax.swing.JLabel();
        jLabelMyProyectIcon = new javax.swing.JLabel();
        jLabelScheduleIcon = new javax.swing.JLabel();
        jLabelPartialReportIcon = new javax.swing.JLabel();
        jLabelMontlyReport = new javax.swing.JLabel();
        jLabelActivitiesPlanIcon = new javax.swing.JLabel();
        jLabelSelfAppraisalIcon = new javax.swing.JLabel();
        jLabelAddPSPIcon = new javax.swing.JLabel();
        jButtonLogout = new javax.swing.JButton();
        jButtonAddMontlyReport = new javax.swing.JButton();
        jButtonAddActivitiesPlan = new javax.swing.JButton();
        jButtonAddSelfAppraisal = new javax.swing.JButton();
        jLabelFound = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitle.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabelTitle.setText("Practicante");
        getContentPane().add(jLabelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, -1, -1));

        jLabelProyectTitle.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabelProyectTitle.setText("Proyecto");
        getContentPane().add(jLabelProyectTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, -1, -1));

        jButtonSelectProyect.setBackground(new java.awt.Color(51, 255, 204));
        jButtonSelectProyect.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonSelectProyect.setText("<html><center>Seleccionar Proyecto");
        jButtonSelectProyect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelectProyectActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSelectProyect, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 150, 70));

        jButtonMyProyect.setBackground(new java.awt.Color(51, 255, 204));
        jButtonMyProyect.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonMyProyect.setText("Mi proyecto");
        getContentPane().add(jButtonMyProyect, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 150, 40));

        jLabelDocumentationTitle.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabelDocumentationTitle.setText("Añadir Documentación");
        getContentPane().add(jLabelDocumentationTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, -1, -1));

        jButtonscheduleAdd.setBackground(new java.awt.Color(51, 255, 204));
        jButtonscheduleAdd.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonscheduleAdd.setText("<html><center>Añadir horario");
        getContentPane().add(jButtonscheduleAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 150, 70));

        jButtonPartialReportAdd.setBackground(new java.awt.Color(51, 255, 204));
        jButtonPartialReportAdd.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonPartialReportAdd.setText("<html><center>Añadir Reporte Parcial");
        getContentPane().add(jButtonPartialReportAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 150, 70));

        jButtonPersonalSoftwareProcessAdd.setBackground(new java.awt.Color(51, 255, 204));
        jButtonPersonalSoftwareProcessAdd.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonPersonalSoftwareProcessAdd.setText("Añadir PSP");
        getContentPane().add(jButtonPersonalSoftwareProcessAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 290, 160, 70));

        jLabelSelectIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/RegisterProyectIcon.png"))); // NOI18N
        getContentPane().add(jLabelSelectIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabelMyProyectIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/MyProyectIcon.png"))); // NOI18N
        getContentPane().add(jLabelMyProyectIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabelScheduleIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/scheduleIcon.png"))); // NOI18N
        getContentPane().add(jLabelScheduleIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, -1, -1));

        jLabelPartialReportIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/reportParcialIcon.png"))); // NOI18N
        getContentPane().add(jLabelPartialReportIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, -1, -1));

        jLabelMontlyReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/reportMontlyIcon.png"))); // NOI18N
        getContentPane().add(jLabelMontlyReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, -1, -1));

        jLabelActivitiesPlanIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/ActivitiesPlanIcon.png"))); // NOI18N
        getContentPane().add(jLabelActivitiesPlanIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, -1, -1));

        jLabelSelfAppraisalIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/selfAppraisalIcon.png"))); // NOI18N
        getContentPane().add(jLabelSelfAppraisalIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, -1, -1));

        jLabelAddPSPIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/AddPSPIcon.png"))); // NOI18N
        getContentPane().add(jLabelAddPSPIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, -1, -1));

        jButtonLogout.setBackground(new java.awt.Color(204, 255, 255));
        jButtonLogout.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonLogout.setText("Cerrar Sesión");
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 400, -1, -1));

        jButtonAddMontlyReport.setBackground(new java.awt.Color(51, 255, 204));
        jButtonAddMontlyReport.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonAddMontlyReport.setText("<html><center>Añadir Reporte Mensual");
        getContentPane().add(jButtonAddMontlyReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 150, 70));

        jButtonAddActivitiesPlan.setBackground(new java.awt.Color(51, 255, 204));
        jButtonAddActivitiesPlan.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonAddActivitiesPlan.setText("<html><center>Añadir Plan de Actividades");
        getContentPane().add(jButtonAddActivitiesPlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, 160, 70));

        jButtonAddSelfAppraisal.setBackground(new java.awt.Color(51, 255, 204));
        jButtonAddSelfAppraisal.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonAddSelfAppraisal.setText("<html><center>Añadir Autoevaluación");
        getContentPane().add(jButtonAddSelfAppraisal, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 200, 160, 70));

        jLabelFound.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/Fondo.jpg"))); // NOI18N
        getContentPane().add(jLabelFound, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSelectProyectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelectProyectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSelectProyectActionPerformed

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        Login returnToLogin = new Login();
        returnToLogin.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalWindowPracticing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalWindowPracticing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalWindowPracticing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalWindowPracticing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalWindowPracticing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddActivitiesPlan;
    private javax.swing.JButton jButtonAddMontlyReport;
    private javax.swing.JButton jButtonAddSelfAppraisal;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonMyProyect;
    private javax.swing.JButton jButtonPartialReportAdd;
    private javax.swing.JButton jButtonPersonalSoftwareProcessAdd;
    private javax.swing.JButton jButtonSelectProyect;
    private javax.swing.JButton jButtonscheduleAdd;
    private javax.swing.JLabel jLabelActivitiesPlanIcon;
    private javax.swing.JLabel jLabelAddPSPIcon;
    private javax.swing.JLabel jLabelDocumentationTitle;
    private javax.swing.JLabel jLabelFound;
    private javax.swing.JLabel jLabelMontlyReport;
    private javax.swing.JLabel jLabelMyProyectIcon;
    private javax.swing.JLabel jLabelPartialReportIcon;
    private javax.swing.JLabel jLabelProyectTitle;
    private javax.swing.JLabel jLabelScheduleIcon;
    private javax.swing.JLabel jLabelSelectIcon;
    private javax.swing.JLabel jLabelSelfAppraisalIcon;
    private javax.swing.JLabel jLabelTitle;
    // End of variables declaration//GEN-END:variables
}
